---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 8.16.0
  nodeSets:
    - name: default
      count: 1
      config:
        # This setting has performance implications. See the README for more details.
        node.store.allow_mmap: false
---
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash
spec:
  count: 1
  version: 8.16.0
  elasticsearchRefs:
    - clusterName: eck
      name: elasticsearch
  podTemplate:
    spec:
      containers:
        - name: logstash
          env:
            - name: ECK_ES_HOSTS
              value: "http://elasticsearch:9200"  # update with your Elasticsearch host(s)
            - name: ECK_ES_USER
              value: "elastic"                   # update with your username
            - name: ECK_ES_PASSWORD
              value: "1mt69b9tn4sNlL3eP97RCM09"                  # update with your password
            - name: ECK_ES_SSL_CERTIFICATE_AUTHORITY
              value: "/usr/share/logstash/config/certs/ca.crt"  # update with the correct CA certificate path
  pipelines:
    - pipeline.id: main
      config.string: |
        tcp {
          port => 5044
          codec => json
        }
        output {
          elasticsearch {
            hosts => [ "${ECK_ES_HOSTS}" ]
            user => "${ECK_ES_USER}"
            password => "${ECK_ES_PASSWORD}"
            ssl_certificate_authorities => "${ECK_ES_SSL_CERTIFICATE_AUTHORITY}"
          }
        }
