apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  labels:
    app: {{ include "elasticsearch.name" . }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.ports.http }}
      name: http
    - port: {{ .Values.service.ports.transport }}
      name: transport
  selector:
    app: {{ include "elasticsearch.name" . }}
