apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "elasticsearch.fullname" . }}
spec:
  serviceName: {{ include "elasticsearch.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "elasticsearch.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "elasticsearch.name" . }}
    spec:
      containers:
        - name: elasticsearch
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.ports.http }}
              name: http
            - containerPort: {{ .Values.service.ports.transport }}
              name: transport
          env:
            - name: discovery.type
              value: "{{ .Values.discovery.type }}"
          volumeMounts:
            - name: storage
              mountPath: /usr/share/elasticsearch/data
              readOnly: false
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
      name: storage
      spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{ .Values.storage.storageClass | quote }}
      resources:
        requests:
        storage: {{ .Values.storage.size }}
    template:
    spec:
      securityContext:
      runAsUser: 1000
      runAsGroup: 0
