replicaCount: 1

image:
  repository: docker.elastic.co/logstash/logstash
  tag: "8.11.1"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

nodeSelector: {}
tolerations: []
affinity: {}

service:
  type: ClusterIP
  port: 5044
  name: logstash

logstashConfig:
  logstash:
    yml: |
      http.host: "0.0.0.0"
      xpack.monitoring.enabled: false

logstashPipeline:
  logstashConf: |
    input {
      tcp {
        port => 5044
        codec => json
      }
    }
    output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "spring-boot-logs-%{+YYYY.MM.dd}"
      }
      stdout { codec => rubydebug }
    }
