apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 5601
    targetPort: 5601
    protocol: TCP
    name: http
  selector:
    app: kibana
    release: {{ .Release.Name }}
