apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app: logstash
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 5044
    targetPort: 5044
    protocol: TCP
    name: beats
  selector:
    app: logstash
    release: {{ .Release.Name }}
