apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-logstash
  labels:
    app: logstash
    release: {{ .Release.Name }}
spec:
  serviceName: "logstash-headless"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: logstash
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: logstash
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: logstash
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 8 }}
        ports:
        - containerPort: 5044
          name: beats
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          subPath: logstash.conf
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-logstash-config
      - name: pipeline
        configMap:
          name: {{ .Release.Name }}-logstash-pipeline
