apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/hamdanfiras/foobar_gitops.git" # Replace with your repo URL
    path: charts/elastic-stack/elasticsearch # Path to the main helm chart directory
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-dev.yaml # Main values file
  destination:
    server: "https://kubernetes.default.svc"
    namespace: logging-dev # Namespace for Elastic Stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logstash
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/hamdanfiras/foobar_gitops.git" # Replace with your repo URL
    path: charts/elastic-stack/logstash # Path to the main helm chart directory
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-dev.yaml # Main values file
  destination:
    server: "https://kubernetes.default.svc"
    namespace: logging-dev # Namespace for Elastic Stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/hamdanfiras/foobar_gitops.git" # Replace with your repo URL
    path: charts/elastic-stack/kibana # Path to the main helm chart directory
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-dev.yaml # Main values file
  destination:
    server: "https://kubernetes.default.svc"
    namespace: logging-dev # Namespace for Elastic Stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
