apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/hamdanfiras/foobar_gitops.git"
    targetRevision: HEAD
    path: charts/foo
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: foo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
