replicaCount: 1

image:
  repository: docker.elastic.co/kibana/kibana
  tag: "8.11.1"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

service:
  type: ClusterIP
  port: 5601

env:
  ELASTICSEARCH_HOSTS: "http://foobar-elasticsearch:9200"

ingress:
  enabled: false # Change to true if using an Ingress controller
  annotations: {}
  hosts:
    - host: kibana.local
      paths:
        - "/"
  tls: []
